[project]
name = "shared"
version = "1.0.0"
description = "Shared code."
requires-python = ">=3.10"
dependencies = [
    "azure-identity>=1.21.0",
    "pydantic>=2.11.3",
    "pydantic-settings>=2.9.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/shared"]

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle
    "C90", # mccabe
    "I", # isort
    "D", # pydocstyle
    "UP", # pyupgrade
    "N", # pep8-naming
    "ERA", # eradicate
    "PL", # Pylint
    "B", # flake8-bugbear
]
ignore = ["D100", "D104", "E501"]  # ignore docstrings in modules & packages and Line too long

[tool.ruff.lint.pydocstyle]
convention = "google"
